Update func/mocoReg, export/make4Dpng files

diff --git a/func/mocoReg b/func/mocoReg
--- a/func/mocoReg
+++ b/func/mocoReg
@@ -37,6 +37,10 @@
 # --fixed handling of voxel spacing
 # -changed the way lack of session variables are handled to be more efficient
 # TODO: Add QC function or source QC script
+# ------------------------------------------------------------------------------
+# UPDATE BY T. KOSCIK 2021-07-21
+# - update logging procedure
+# - add inputs to specify native anatomical better
 #===============================================================================
 PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
 FCN_NAME=($(basename "$0"))
@@ -76,9 +80,11 @@ trap egress EXIT
 # Parse inputs -----------------------------------------------------------------
 OPTS=$(getopt -o hvkln --long prefix:,\
 ts-bold:,\
-native-anat:,native-mod:,native-mask:,which-mask:,native-align:,\
+native-anat:,native-mod:,native-mask:,which-mask:,\
+xfm-align:,xfm-norm:,\
 template:,template_mod:,space:,\
-dir-save:,dir-scratch:,\
+pad:,\
+dir-xfm:,dir-save:,dir-scratch:,\
 keep,help,verbose,no-log,no-png -n 'parse-options' -- "$@")
 if [[ $? != 0 ]]; then
   echo "Failed parsing options" >&2
@@ -92,11 +98,14 @@ TS_BOLD=
 NATIVE_ANAT=
 NATIVE_MOD=T1w
 NATIVE_MASK=
-WHICH_MASK=ANTs
-NATIVE_ALIGN=
+WHICH_MASK=mask-brain+ANTs
+XFM_ALIGN=
+XFM_NORM=
 TEMPLATE=HCPICBM
 TEMPLATE_MOD=T1w
 SPACE=2mm
+PAD=5
+DIR_XFM=
 DIR_SAVE=
 DIR_SCRATCH=${INC_SCRATCH}/${OPERATOR}_${DATE_SUFFIX}
 HELP=false
@@ -117,10 +126,12 @@ while true; do
     --native-mod) NATIVE_MOD="$2" ; shift 2 ;;
     --native-mask) NATIVE_MASK="$2" ; shift 2 ;;
     --which-mask) WHICH_MASK="$2" ; shift 2 ;;
-    --native-align) NATIVE_ALIGN="$2" ; shift 2 ;;
+    --xfm-align) XFM_ALIGN="$2" ; shift 2 ;;
+    --xfm-norm) XFM_NORM="$2" ; shift 2 ;;
     --template) TEMPLATE="$2" ; shift 2 ;;
     --template-mod) TEMPLATE_MOD="$2" ; shift 2 ;;
     --space) SPACE="$2" ; shift 2 ;;
+    --pad) PAD="$2" ; shift 2 ;;
     --dir-save) DIR_SAVE="$2" ; shift 2 ;;
     --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
     -- ) shift ; break ;;
@@ -174,53 +185,64 @@ fi
 mkdir -p ${DIR_SCRATCH}
 mkdir -p ${DIR_SAVE}
 
-# Native anatomical, brain mask, and rigid alignment transform - - - - - - - - -
+# check XFM directory
+if [[ -z ${DIR_XFM} ]]; then
+  DIR_XFM=${DIR_PROJECT}/derivatives/inc/xfm/${DIRPID}
+fi
+
+# get native anatomical --------------------------------------------------------
 if [[ -z ${NATIVE_ANAT} ]]; then
-  NATIVE_ANAT=($(ls ${DIR_ANAT}/native/${PIDSTR}*${NATIVE_MOD}.nii.gz))
+  NATIVE_ANAT=($(ls ${DIR_PROJECT}/derivatives/inc/anat/native/${PIDSTR}*${NATIVE_MOD}.nii.gz))
 fi
 if [[ -z ${NATIVE_ANAT} ]] || [[ ! -f ${NATIVE_ANAT} ]]; then
   echo "Native anatomical not found, aborting."
   exit 1
 fi
 
+# get native mask --------------------------------------------------------------
 if [[ -z ${NATIVE_MASK} ]]; then
-  NATIVE_MASK=($(ls ${DIR_ANAT}/mask/${PIDSTR}*mask-brain*${WHICH_MASK}*.nii.gz))
+  NATIVE_MASK=($(ls ${DIR_PROJECT}/derivatives/inc/anat/mask/${PIDSTR}*${WHICH_MASK}.nii.gz))
 fi
 if [[ -z ${NATIVE_MASK} ]] || [[ ! -f ${NATIVE_MASK} ]]; then
   echo "Native anatomical mask not found, aborting."
   exit 1
 fi
-#####################
-DIR_XFM=${DIR_PROJECT}/derivatives/inc/xfm/${DIRPID}
-XFM_ALIGN=($(ls ${DIR_XFM}/${PIDSTR}*from-native_to-${TEMPLATE}*_xfm-rigid.mat))
-if [[ -n "${XFM_ALIGN}" ]]; then
-  INIT_XFM=${XFM_ALIGN}
-else
-  echo "Alignment registration not found, continuing."
-  INIT_XFM=[${ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1]
+
+# get alignment xfm ------------------------------------------------------------
+if [[ -z ${XFM_ALIGN} ]]; then
+  XFM_ALIGN=($(ls ${DIR_PROJECT}/derivatives/inc/xfm/${DIRPID}/${PIDSTR}*from-native_to-${TEMPLATE}*_xfm-rigid.mat))
+fi
+if [[ -z "${XFM_ALIGN}" ]]; then
+  echo "Alignment registration not found, continuing with ANTs default initialization."
+  XFM_ALIGN=[${NATIVE_ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1]
 fi
 
-# Find transforms - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-unset XFM_LS XFM_ARG XFM_NORM
-XFM_LS=($(ls ${DIR_XFM}/*native_to-${TEMPLATE}* 2>/dev/null))
-if [[ -z "${XFM_LS}" ]]; then
-  # note: the line below is for backward compatibility with slightly different naming scheme
-  XFM_LS=($(ls ${DIR_XFM}/*${TARGET}+rigid_to-${TEMPLATE}* 2>/dev/null))
-  if [[ -z "${XFM_LS}" ]]; then
-    echo "Normalization transform(s) not found, aborting"
-    exit 1
-  fi
+# get normalization transforms -------------------------------------------------
+if [[ -z ${XFM_NORM} ]]; then
+  XFM_NORM=($(ls ${DIR_PROJECT}/derivatives/inc/xfm/${DIRPID}/*native_to-${TEMPLATE}*))
+fi
+## for backwards compatibility with different naming schemes
+if [[ -z ${XFM_NORM} ]]; then
+  XFM_NORM=($(ls ${DIR_PROJECT}/derivatives/inc/xfm/${DIRPID}/*${TARGET}+rigid_to-${TEMPLATE}*))
+fi
+if [[ -z ${XFM_NORM} ]]; then
+  XFM_NORM=($(ls ${DIR_PROJECT}/derivatives/xfm/${DIRPID}/*${TARGET}+rigid_to-${TEMPLATE}*))
+fi
+if [[ -z "${XFM_NORM}" ]]; then
+  echo "Normalization transform(s) not found, aborting"
+  exit 1
 fi
 
 unset XFM_STACK XFM_RIGID XFM_AFFINE XFM_SYN
-for (( i=0; i<${#XFM_LS[@]}; i++ )); do
+for (( i=0; i<${#XFM_NORM[@]}; i++ )); do
   unset XFM_ARG
-  XFM_ARG=$(getField -i ${XFM_LS[${i}]} -f xfm)
-  if [[ "${XFM_ARG,,}" == "rigid" ]]; then XFM_RIGID=${XFM_LS[${i}]}; fi
-  if [[ "${XFM_ARG,,}" == "affine" ]]; then XFM_AFFINE=${XFM_LS[${i}]}; fi
-  if [[ "${XFM_ARG,,}" == "syn" ]]; then XFM_SYN=${XFM_LS[${i}]}; fi
-  if [[ "${XFM_ARG,,}" == "stack" ]]; then XFM_STACK=${XFM_LS[${i}]}; fi
+  XFM_ARG=$(getField -i ${XFM_NORM[${i}]} -f xfm)
+  if [[ "${XFM_ARG,,}" == "rigid" ]]; then XFM_RIGID=${XFM_NORM[${i}]}; fi
+  if [[ "${XFM_ARG,,}" == "affine" ]]; then XFM_AFFINE=${XFM_NORM[${i}]}; fi
+  if [[ "${XFM_ARG,,}" == "syn" ]]; then XFM_SYN=${XFM_NORM[${i}]}; fi
+  if [[ "${XFM_ARG,,}" == "stack" ]]; then XFM_STACK=${XFM_NORM[${i}]}; fi
 done
+unset XFM_NORM
 if [[ -n "${XFM_STACK}" ]]; then 
   XFM_NORM=${XFM_STACK}
 else
@@ -232,48 +254,56 @@ N_XFM=${#XFM_NORM[@]}
 
 # Motion Correction + registration ============================================
 # Get timeseries info ---------------------------------------------------------
-NUM_TR=$(niiInfo -i ${TS_BOLD} -f numTR)
+NTR=$(niiInfo -i ${TS_BOLD} -f numTR)
 TR=$(niiInfo -i ${TS_BOLD} -f TR)
 # check in here for 4d file.
-if [[ "${NUM_TR}" == 1 ]]; then
+if [[ "${NTR}" == 1 ]]; then
   echo "Input file is not a 4D file. Aborting."
   exit 1
 fi
 
-# Motion correction -----------------------------------------------------------
-# pad image for better registration - - - - - - - - - - - - - - - - - - - - - -
-fslsplit ${TS_BOLD} ${DIR_SCRATCH}/vol -t
-for (( i=0; i<${NUM_TR}; i++ )); do
-  VOL_NUM=$(printf "%04d" ${i})
-  ImageMath 3 ${DIR_SCRATCH}/vol${VOL_NUM}.nii.gz PadImage ${DIR_SCRATCH}/vol${VOL_NUM}.nii.gz 5
-done
-MERGE_LS=($(ls ${DIR_SCRATCH}/vol*))
-fslmerge -tr ${DIR_SCRATCH}/${PREFIX}_bold+pad.nii.gz ${MERGE_LS[@]} ${TR}
-TS_BOLD=${DIR_SCRATCH}/${PREFIX}_bold+pad.nii.gz
-rm ${MERGE_LS[@]}
+# Motion correction ===========================================================
+# pad image for better registration -------------------------------------------
+if [[ ${PAD} -ne 0 ]]; then
+  fslsplit ${TS_BOLD} ${DIR_SCRATCH}/vol -t
+  for (( i=0; i<${NTR}; i++ )); do
+    NV=$(printf "%04d" ${i})
+    ImageMath 3 ${DIR_SCRATCH}/vol${NV}.nii.gz \
+      PadImage ${DIR_SCRATCH}/vol${NV}.nii.gz ${PAD}
+  done
+  MERGE_LS=($(ls ${DIR_SCRATCH}/vol*))
+  fslmerge -tr ${DIR_SCRATCH}/${PREFIX}_bold+pad.nii.gz ${MERGE_LS[@]} ${TR}
+  TS_BOLD=${DIR_SCRATCH}/${PREFIX}_bold+pad.nii.gz
+  rm ${MERGE_LS[@]}
+fi
 
-# calculate mean BOLD - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# initialize mean BOLD ---------------------------------------------------------
 antsMotionCorr -d 3 -a ${TS_BOLD} -o ${DIR_SCRATCH}/${PREFIX}_avg.nii.gz
 
-# Rigid registration to mean BOLD - - - - - - - - - - - - - - - - - - - - - - -
-## to refine any large motions out of average
+# rigid body motion correction to mean BOLD (6 df) -----------------------------
 antsMotionCorr \
-  -d 3 -u 1 -e 1 -n ${NUM_TR} -v ${VERBOSE} \
+  -d 3 -u 1 -e 1 -n ${NTR} -v ${VERBOSE} \
   -o [${DIR_SCRATCH}/${PREFIX}_rigid_,${DIR_SCRATCH}/${PREFIX}.nii.gz,${DIR_SCRATCH}/${PREFIX}_avg.nii.gz] \
-  -t Rigid[0.1] -m MI[${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
-  -i 20x15x5x1 -s 3x2x1x0 -f 4x3x2x1
+  -t Rigid[0.1]
+  -m MI[${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
+  -i 20x15x5x1
+  -s 3x2x1x0
+  -f 4x3x2x1
 
 cat ${DIR_SCRATCH}/${PREFIX}_rigid_MOCOparams.csv | tail -n+2 > ${DIR_SCRATCH}/temp.csv
 cut -d, -f1-2 --complement ${DIR_SCRATCH}/temp.csv > ${DIR_SCRATCH}/${PREFIX}_moco+6.1D
 rm ${DIR_SCRATCH}/temp.csv
 rm ${DIR_SCRATCH}/${PREFIX}_rigid_MOCOparams.csv
 
-# Affine registration to mean BOLD - - - - - - - - - - - - - - - - - - - - - - -
+# Affine registration to mean BOLD ---------------------------------------------
 antsMotionCorr \
-  -d 3 -u 1 -e 1 -n ${NUM_TR} -l 1 -v ${VERBOSE} \
+  -d 3 -u 1 -e 1 -n ${NTR} -l 1 -v ${VERBOSE} \
   -o [${DIR_SCRATCH}/${PREFIX}_affine_,${DIR_SCRATCH}/${PREFIX}.nii.gz,${DIR_SCRATCH}/${PREFIX}_avg.nii.gz] \
-  -t Affine[0.1] -m MI[${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
-  -i 20x15x5x1 -s 3x2x1x0 -f 4x3x2x1
+  -t Affine[0.1] \
+  -m MI[${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
+  -i 20x15x5x1 \
+  -s 3x2x1x0 \
+  -f 4x3x2x1
 
 cat ${DIR_SCRATCH}/${PREFIX}_affine_MOCOparams.csv | tail -n+2 > ${DIR_SCRATCH}/temp.csv
 cut -d, -f1-2 --complement ${DIR_SCRATCH}/temp.csv > ${DIR_SCRATCH}/${PREFIX}_moco+12.1D
@@ -290,26 +320,45 @@ mv ${DIR_SCRATCH}/${PREFIX}_mask-brain_mask.nii.gz \
 antsRegistration \
   -d 3 -u 0 -z 1 -l 1 -n Linear -v ${VERBOSE} \
   -o ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_ \
-  -r ${INIT_XFM} \
+  -r ${XFM_ALIGN} \
   -t Rigid[0.25] \
-  -m Mattes[${ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1,32,Regular,0.2] \
-  -c [1200x1200x100,1e-6,5] -f 4x2x1 -s 2x1x0vox \
-  -x [${ANAT_MASK},${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz] \
+    -m Mattes[${NATIVE_ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1,32,Regular,0.2] \
+    -c [1200x1200x100,1e-6,5] \
+    -f 4x2x1 \
+    -s 2x1x0vox \
+    -x [${NATIVE_MASK},${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz] \
   -t Affine[0.25] \
-  -m Mattes[${ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1,32,Regular,0.2] \
-  -c [200x20,1e-6,5] -f 2x1 -s 1x0vox \
-  -x [${ANAT_MASK},${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz] \
+    -m Mattes[${NATIVE_ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1,32,Regular,0.2] \
+    -c [200x20,1e-6,5] \
+    -f 2x1 \
+    -s 1x0vox \
+    -x [${NATIVE_MASK},${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz] \
   -t SyN[0.2,3,0] \
-  -m Mattes[${ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1,32] \
-  -c [40x20x0,1e-7,8] -f 4x2x1 -s 2x1x0vox \
-  -x [${ANAT_MASK},${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz]
+    -m Mattes[${NATIVE_ANAT},${DIR_SCRATCH}/${PREFIX}_avg.nii.gz,1,32] \
+    -c [40x20x0,1e-7,8] \
+    -f 4x2x1 \
+    -s 2x1x0vox \
+    -x [${NATIVE_MASK},${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz]
 
-# collapse transforms to deformation field - - - - - - - - - - - - - - - - - - -
-antsApplyTransforms -d 3 \
-  -o [${DIR_SCRATCH}/${PREFIX}_xfm_toNative_stack.nii.gz,1] \
-  -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_1Warp.nii.gz \
-  -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_0GenericAffine.mat \
-  -r ${ANAT}
+# check if desired space template exists, if not resample ----------------------
+TRG=${INC_TEMPLATE}/${TEMPLATE}/${SPACE}/${TEMPLATE}_${SPACE}_${TEMPLATE_MOD}.nii.gz
+if [[  -f ${TRG} ]]; then
+  ## find highest resolution version of template
+  MINSZ=99999
+  SZ=($(ls ${INC_TEMPLATE}/${TEMPLATE}))
+  for (( i=0; i<${#SZ[@]}; i++ )); do
+    if [[ "${SZ[${i}]}" == *"mm"* ]];
+      SZ[${i}]=$(ezMath -x "${SZ[${i}]::-2}*1000" -d 0)
+    else
+      SZ[${i}]=$(echo ${SZ[${i}]::-2})
+    fi
+    if [[ ${SZ[${i}]} -lt ${MINSZ} ]]; then MINSZ=${SZ[${i}]}; fi
+  done
+  ResampleImage 3 ${TRG} \
+    ${DIR_SCRATCH}/template_resampled_${SPACE}.nii.gz \
+    "${SPACE}x${SPACE}x${SPACE}" 0 0 6
+  TRG=${DIR_SCRATCH}/template_resampled_${SPACE}.nii.gz
+fi
 
 # Push mean bold to template ---------------------------------------------------
 unset xfm_fcn
@@ -319,8 +368,9 @@ xfm_fcn="${xfm_fcn} -i ${DIR_SCRATCH}/${PREFIX}_avg.nii.gz"
 for (( i=0; i<${N_XFM}; i++ )); do
   xfm_fcn="${xfm_fcn} -t ${XFM_NORM}"
 done
-xfm_fcn="${xfm_fcn} -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_stack.nii.gz"
-xfm_fcn="${xfm_fcn} -r ${INC_TEMPLATE}/${TEMPLATE}/${SPACE}/${TEMPLATE}_${SPACE}_T1w.nii.gz"
+xfm_fcn="${xfm_fcn} -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_1Warp.nii.gz"
+xfm_fcn="${xfm_fcn} -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_0GenericAffine.mat"
+xfm_fcn="${xfm_fcn} -r ${TRG}"
 eval ${xfm_fcn}
 
 # apply to brain mask as well - - - - - - - - - - - - - - - - - - - - - - - - - 
@@ -331,39 +381,50 @@ xfm_fcn="${xfm_fcn} -i ${DIR_SCRATCH}/${PREFIX}_mask-brain.nii.gz"
 for (( i=0; i<${N_XFM}; i++ )); do
   xfm_fcn="${xfm_fcn} -t ${XFM_NORM}"
 done
-xfm_fcn="${xfm_fcn} -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_stack.nii.gz"
-xfm_fcn="${xfm_fcn} -r ${INC_TEMPLATE}/${TEMPLATE}/${SPACE}/${TEMPLATE}_${SPACE}_T1w.nii.gz"
+xfm_fcn="${xfm_fcn} -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_1Warp.nii.gz"
+xfm_fcn="${xfm_fcn} -t ${DIR_SCRATCH}/${PREFIX}_xfm_toNative_0GenericAffine.mat"
+xfm_fcn="${xfm_fcn} -r ${TRG}"
 eval ${xfm_fcn}
 
 # redo motion correction to normalized mean bold ------------------------------
 antsMotionCorr \
-  -d 3 -u 1 -e 1 -n ${NUM_TR} -l 1 -v ${VERBOSE} \
+  -d 3 -u 1 -e 1 -n ${NTR} -l 1 -v ${VERBOSE} \
   -o [${DIR_SCRATCH}/${PREFIX}_moco+warp_,${DIR_SCRATCH}/${PREFIX}_moco+warp.nii.gz,${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz] \
-  -t Rigid[0.25] -m MI[${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
-  -i 20x15x5x1 -s 3x2x1x0 -f 4x3x2x1 \
-  -t Affine[0.25] -m MI[${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
-  -i 20x15x5x1 -s 3x2x1x0 -f 4x3x2x1 \
-  -t SyN[0.2,3,0] -m MI[${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
-  -i 20x15x5x1 -s 3x2x1x0 -f 4x3x2x1
+  -t Rigid[0.25] \
+    -m MI[${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
+    -i 20x15x5x1 \
+    -s 3x2x1x0 \
+    -f 4x3x2x1 \
+  -t Affine[0.25] \
+    -m MI[${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
+    -i 20x15x5x1 \
+    -s 3x2x1x0 \
+    -f 4x3x2x1 \
+  -t SyN[0.2,3,0] \
+    -m MI[${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz,${TS_BOLD},1,32,Regular,0.2] \
+    -i 20x15x5x1 \
+    -s 3x2x1x0 \
+    -f 4x3x2x1
 
 # Depad images ----------------------------------------------------------------
-fslsplit ${DIR_SCRATCH}/${PREFIX}_moco+warp.nii.gz ${DIR_SCRATCH}/vol -t
-for (( i=0; i<${NUM_TR}; i++ )); do
-  VOL_NUM=$(printf "%04d" ${i})
-  ImageMath 3 ${DIR_SCRATCH}/vol${VOL_NUM}.nii.gz \
-    PadImage ${DIR_SCRATCH}/vol${VOL_NUM}.nii.gz -5
-done
-MERGE_LS=($(ls ${DIR_SCRATCH}/vol*))
-fslmerge -tr ${DIR_SCRATCH}/${PREFIX}_bold.nii.gz ${MERGE_LS[@]} ${TR}
-rm ${MERGE_LS[@]}
+if [[ ${PAD} -ne 0 ]]; then 
+  DEPAD=$(ezMath -x "${PAD} * -1" -d 0)
+  fslsplit ${DIR_SCRATCH}/${PREFIX}_moco+warp.nii.gz ${DIR_SCRATCH}/vol -t
+  for (( i=0; i<${NTR}; i++ )); do
+    NV=$(printf "%04d" ${i})
+    ImageMath 3 ${DIR_SCRATCH}/vol${NV}.nii.gz \
+      PadImage ${DIR_SCRATCH}/vol${NV}.nii.gz ${DEPAD}
+  done
+  MERGE_LS=($(ls ${DIR_SCRATCH}/vol*))
+  fslmerge -tr ${DIR_SCRATCH}/${PREFIX}_bold.nii.gz ${MERGE_LS[@]} ${TR}
+  rm ${MERGE_LS[@]}
+fi
 
 # Move files to appropriate locations -----------------------------------------
 DIR_REGRESSOR=${DIR_SAVE}/regressors/${DIRPID}
 mkdir -p ${DIR_REGRESSOR}
-
 sed -i 's/,/\t/g' ${DIR_SCRATCH}/${PREFIX}_moco+6.1D
 sed -i 's/,/\t/g' ${DIR_SCRATCH}/${PREFIX}_moco+12.1D
-
 mv ${DIR_SCRATCH}/${PREFIX}_moco+6.1D ${DIR_REGRESSOR}/${PREFIX}_reg-${TEMPLATE}+${SPACE}_moco+6.1D
 mv ${DIR_SCRATCH}/${PREFIX}_moco+12.1D ${DIR_REGRESSOR}/${PREFIX}_reg-${TEMPLATE}+${SPACE}_moco+12.1D
 
@@ -377,13 +438,29 @@ mkdir -p ${DIR_SAVE}/moco_${TEMPLATE}+${SPACE}
 mv ${DIR_SCRATCH}/${PREFIX}_moco+warp.nii.gz \
   ${DIR_SAVE}/moco_${TEMPLATE}+${SPACE}/${PREFIX}_reg-${TEMPLATE}+${SPACE}_bold.nii.gz
 
-mkdir -p ${DIR_SAVE}/moco_${TEMPLATE}+${SPACE}_mean
+mkdir -p ${DIR_SAVE}/mean_${TEMPLATE}+${SPACE}
 mv ${DIR_SCRATCH}/${PREFIX}_avg+warp.nii.gz \
-  ${DIR_SAVE}/moco_${TEMPLATE}+${SPACE}_mean/${PREFIX}_reg-${TEMPLATE}+${SPACE}_proc-mean_bold.nii.gz
+  ${DIR_SAVE}/mean_${TEMPLATE}+${SPACE}/${PREFIX}_reg-${TEMPLATE}+${SPACE}_proc-mean_bold.nii.gz
 
 if [[ "${KEEP}" == "true" ]]; then
   mkdir -p ${DIR_SAVE}/prep/${DIRPID}
   mv ${DIR_SCRATCH}/* ${DIR_SAVE}/prep/${DIRPID}/
+fi
+
+# generate output PNGs ---------------------------------------------------------
+if [[ "${NO_PNG}" == "false" ]]; then
+  ## mean bold overlay on template, masked with brain mask
+  make3Dpng --bg ${TRG} \
+    --fg ${DIR_SAVE}/mean_${TEMPLATE}+${SPACE}/${PREFIX}_reg-${TEMPLATE}+${SPACE}_proc-mean_bold.nii.gz \
+    --fg-mask ${DIR_SAVE}/mask/${PREFIX}_reg-${TEMPLATE}+${SPACE}_acq-bold_mask-brain.nii.gz \
+    --fg-color "hot" \
+    --layout "9:x;9:x;9:x;9:y;9:y;9:y;9:z;9:z;9:z" \
+    --offset "0,0,0"
+  ## image of slices in 4d
+  make4Dpng --bg ${TRG} \
+    --fg ${DIR_SAVE}/moco_${TEMPLATE}+${SPACE}/${PREFIX}_reg-${TEMPLATE}+${SPACE}_bold.nii.gz \
+    --fg-mask ${DIR_SAVE}/mask/${PREFIX}_reg-${TEMPLATE}+${SPACE}_acq-bold_mask-brain.nii.gz \
+    --fg-color "hot" --layout "5x11" --plane "z" --slice 0.51
 fi
 
 #===============================================================================
