commit fixes

diff --git a/anat/coregistrationChef b/anat/coregistrationChef
--- a/anat/coregistrationChef
+++ b/anat/coregistrationChef
@@ -42,24 +42,58 @@ function egress {
 trap egress EXIT
 
 # Parse inputs -----------------------------------------------------------------
-OPTS=$(getopt -o hvldn --long recipe-json:,recipe-name:,\
-fixed:,fixed-mask:,fixed-mask-dilation:,\
-moving:,moving-mask:,moving-mask-dilation:,mask-procedure:,\
-dir-template:,template:,space-source:,space-target:,\
-\
-dimensonality:,save-state:,restore-state:,write-composite-transform,\
-print-similarity-measure-interval:,write-internal-volumes:,\
-collapse-output-transforms,initialize-transforms-per-stage,interpolation:,\
-restrict-deformation:,initial-fixed-transform:,initial-moving-transform:,metric:,\
-transform:,convergence:,smoothing-sigmas:,shrink-factors:,use-histogram-matching:,\
-use-estimate-learning-rate-once,winsorize-image-intensities:,float,random-seed:,\
+OPTS=$(getopt -o hvldn --long recipe-json:,\
+recipe-name:,\
+fixed:,\
+fixed-mask:,\
+fixed-mask-dilation:,\
+moving:,\
+moving-mask:,\
+moving-mask-dilation:,\
+mask-procedure:,\
+dir-template:,\
+template:,\
+space-source:,\
+space-target:,\
+dimensonality:,\
+save-state:,\
+restore-state:,\
+write-composite-transform,\
+print-similarity-measure-interval:,\
+write-internal-volumes:,\
+collapse-output-transforms,\
+initialize-transforms-per-stage,\
+interpolation:,\
+restrict-deformation:,\
+initial-fixed-transform:,\
+initial-moving-transform:,metric:,\
+transform:,\
+convergence:,\
+smoothing-sigmas:,\
+shrink-factors:,\
+use-histogram-matching:,\
+use-estimate-learning-rate-once,\
+winsorize-image-intensities:,\
+float,\
+random-seed:,\
 ants-verbose,\
-\
-prefix:,label-xfm:,label-from:,label-to:,label-reg:,\
-apply-to:,apply-to-name:,\
-keep-fwd-xfm,keep-inv-xfm,\
-dir-save:,dir-xfm:,dir-scratch:,\
-verbose,help,no-log,dry-run,no-png -n 'parse-options' -- "$@")
+prefix:,\
+label-xfm:,\
+label-from:,\
+label-to:,\
+label-reg:,\
+apply-to:,\
+apply-to-name:,\
+keep-fwd-xfm,\
+keep-inv-xfm,\
+dir-save:,\
+dir-xfm:,\
+dir-scratch:,\
+verbose,\
+help,\
+no-log,\
+dry-run,\
+no-png -n 'parse-options' -- "$@")
 if [ $? != 0 ]; then
   echo "Failed parsing options" >&2
   exit 1
@@ -83,7 +117,7 @@ while true; do
     --recipe-name) RECIPE_NAME="$2" ; shift 2 ;;
     --fixed) FIXED="$2" ; shift 2 ;;
     --fixed-mask) FIXED_MASK="$2" ; shift 2 ;;
-    --fixed-mask-dilation) FIXED_MASK="$2" ; shift 2 ;;
+    --fixed-mask-dilation) FIXED_MASK_DILATION="$2" ; shift 2 ;;
     --moving) MOVING="$2" ; shift 2 ;;
     --moving-mask) MOVING_MASK="$2" ; shift 2 ;;
     --moving-mask-dilation) MOVING_MASK_DILATION="$2" ; shift 2 ;;
@@ -345,16 +379,21 @@ if [[ "${MOVING_MASK[0]}" != "optional" ]]; then
       MOVING_MASK[${i}]=${DIR_SCRATCH}/MOVING_MASK_${i}_${TMOD}.nii.gz
     done
   fi
-  if [[ ${#MOVING_MASK[@]} -eq 1 ]] && [[ ${#MOVING[@]} -gt 1 ]]; then
-    for (( i=1; i<${#MOVING[@]}; i++ )); do
-      MOVING_MASK+=(${MOVING_MASK[0]})
-    done
-  fi
+#  if [[ ${#MOVING_MASK[@]} -eq 1 ]] && [[ ${#MOVING[@]} -gt 1 ]]; then
+#    for (( i=1; i<${#MOVING[@]}; i++ )); do
+#      MOVING_MASK+=(${MOVING_MASK[0]})
+#    done
+#  fi
   if [[ "${MASK_PROCEDURE,,}" == *"apply"* ]]; then
     for (( i=0; i<${#MOVING[@]}; i++ )); do
       TMOD=$(getField -i ${MOVING[${i}]} -f modality)
-      fslmaths ${MOVING[${i}]} -mas ${MOVING_MASK[${i}]} ${DIR_SCRATCH}/MOVING_${i}_${TMOD}.nii.gz
-      MOVING[${i}]=${DIR_SCRATCH}/MOVING_${i}_${TMOD}.nii.gz
+      if [[ ${#MOVING_MASK[@]} -eq 1 ]]; then
+        fslmaths ${MOVING[${i}]} -mas ${MOVING_MASK[0]} ${DIR_SCRATCH}/MOVING_${i}_${TMOD}.nii.gz
+        MOVING[${i}]=${DIR_SCRATCH}/MOVING_${i}_${TMOD}.nii.gz
+      else
+        echo "ERROR [INC ${FCN_NAME}] pre-applying multiple masks on multiple input images is not supported. IT is unclear what the purpose or result of this would even be."
+        exit 5
+      fi
     done
   fi
 fi
@@ -367,7 +406,6 @@ if [[ "${FIXED_MASK[0]}" != "optional" ]]; then
     exit 5
   fi
   if [[ ${FIXED_MASK_DILATION} -ne 0 ]]; then
-  echo "test1"
     for (( i=0; i<${#FIXED_MASK[@]}; i++ )); do
       TMOD=$(getField -i ${FIXED_MASK[${i}]} -f modality)
       ImageMath 3 ${DIR_SCRATCH}/FIXED_MASK_${i}_${TMOD}.nii.gz \
@@ -376,7 +414,6 @@ if [[ "${FIXED_MASK[0]}" != "optional" ]]; then
     done
   fi
   if [[ "${FIX_SPACE}" == "true" ]]; then
-  echo "test2" 
     for (( i=0; i<${#FIXED_MASK[@]}; i++ )); do
       TMOD=$(getField -i ${FIXED_MASK[${i}]} -f modality)
       if [[ "${DRY_RUN}" == "false" ]]; then
@@ -389,17 +426,22 @@ if [[ "${FIXED_MASK[0]}" != "optional" ]]; then
       FIXED_MASK[${i}]=${DIR_SCRATCH}/FIXED_MASK_${i}_${TMOD}.nii.gz
     done
   fi
-  if [[ ${#FIXED_MASK[@]} -eq 1 ]] && [[ ${#FIXED[@]} -gt 1 ]]; then
-    for (( i=1; i<${#FIXED[@]}; i++ )); do
-      FIXED_MASK+=(${FIXED_MASK[0]})
-    done
-  fi
+#  if [[ ${#FIXED_MASK[@]} -eq 1 ]] && [[ ${#FIXED[@]} -gt 1 ]]; then
+#    for (( i=1; i<${#FIXED[@]}; i++ )); do
+#      FIXED_MASK+=(${FIXED_MASK[0]})
+#    done
+#  fi
   if [[ "${MASK_PROCEDURE,,}" == *"apply"* ]]; then
-  echo "test3"
     for (( i=0; i<${#FIXED[@]}; i++ )); do
       TMOD=$(getField -i ${FIXED[${i}]} -f modality)
-      fslmaths ${FIXED[${i}]} -mas ${FIXED_MASK[${i}]} ${DIR_SCRATCH}/FIXED_${i}_${TMOD}.nii.gz
-      FIXED[${i}]=${DIR_SCRATCH}/FIXED_${i}_${TMOD}.nii.gz
+      if [[ ${#FIXED_MASK[@]} -eq 1 ]]; then
+        fslmaths ${FIXED[${i}]} -mas ${FIXED_MASK[0]} ${DIR_SCRATCH}/FIXED_${i}_${TMOD}.nii.gz
+        FIXED[${i}]=${DIR_SCRATCH}/FIXED_${i}_${TMOD}.nii.gz
+      else
+        echo "ERROR [INC ${FCN_NAME}] pre-applying multiple masks on multiple input images is not sup
+ported. IT is unclear what the purpose or result of this would even be."
+        exit 5
+      fi
     done
   fi
 fi
@@ -604,6 +646,9 @@ elif [[ "${INITIAL_MOVING_TRANSFORM}" != "optional" ]]; then
     antsCoreg="${antsCoreg} --initial-moving-transform ${INITIAL_MOVING_TRANSFORM[${i}]}"
   done
 fi
+
+echo -e "\n${FIXED_MASK[@]}\n${MOVING_MASK[@]}\n"}
+
 if [[ "${MASK_PROCEDURE}" == "restrict" ]] \
 && [[ "${FIXED_MASK[0]}" != "optional" ]] \
 && [[ ${#FIXED_MASK[@]} -eq 1 ]]; then
@@ -647,11 +692,8 @@ antsCoreg="${antsCoreg} --random-seed ${RANDOM_SEED}"
 if [[ "${VERBOSE}" == "true" ]]; then echo " DONE"; fi
 
 if [[ "${DRY_RUN}" == "true" ]] || [[ "${VERBOSE}" == "true" ]]; then
-  echo ""
-  echo "ANTs Coregistration Call -------------------------------------------------------"
-  echo ""
-  echo "${antsCoreg}"
-  echo ""
+  echo -e "\nANTs Coregistration Call -------------------------------------------------------"
+  echo -e "\n${antsCoreg//--/\n--}\n"
 fi
 if [[ "${DRY_RUN}" == "true" ]]; then
   exit 0
@@ -747,6 +789,7 @@ fi
 
 # generate PNG -----------------------------------------------------------------
 if [[ "${NO_PNG}" == "false" ]]; then
+  if [[ "${VERBOSE}" == "true" ]]; then echo -ne ">>>make PNGs"; fi
   make3Dpng \
     --bg ${DIR_SAVE}/${MOVING_OUTPUT[${i}]} \
       --bg-thresh "5,99" \
@@ -757,9 +800,29 @@ if [[ "${NO_PNG}" == "false" ]]; then
       --bg-thresh "10,95" \
     --fg ${DIR_SAVE}/${MOVING_OUTPUT[${i}]} \
       --fg-thresh "10,95" --fg-color "#000000,#FF00FF,#FFFFFF" --fg-alpha 50 --fg-cbar \
-    --layout "7:x;7:y;7:z" --offset "0,0,0" \
-    --filename "${PIDSTR}_${LABEL_REG}" \
-    --dir-save ${DIR_SAVE}
+    --layout "7:x;7:x;7:x;7:x;7:x" --offset "0,0,0" \
+    --filename "${PIDSTR}_${LABEL_REG}_X" \
+    --dir-save ${DIR_XFM}
+  make3Dpng \
+    --bg ${FIXED[0]} \
+      --bg-color "#000000,#00FF00,#FFFFFF" \
+      --bg-thresh "10,95" \
+    --fg ${DIR_SAVE}/${MOVING_OUTPUT[${i}]} \
+      --fg-thresh "10,95" --fg-color "#000000,#FF00FF,#FFFFFF" --fg-alpha 50 --fg-cbar \
+    --layout "7:y;7:y;7:y;7:y;7:y" --offset "0,0,0" \
+    --filename "${PIDSTR}_${LABEL_REG}_Y" \
+    --dir-save ${DIR_XFM}
+  make3Dpng \
+    --bg ${FIXED[0]} \
+      --bg-color "#000000,#00FF00,#FFFFFF" \
+      --bg-thresh "10,95" \
+    --fg ${DIR_SAVE}/${MOVING_OUTPUT[${i}]} \
+      --fg-thresh "10,95" --fg-color "#000000,#FF00FF,#FFFFFF" --fg-alpha 50 --fg-cbar \
+    --layout "7:z;7:z;7:z;7:z;7:z" --offset "0,0,0" \
+    --filename "${PIDSTR}_${LABEL_REG}_Z" \
+    --dir-save ${DIR_XFM}
+
+  if [[ "${VERBOSE}" == "true" ]]; then echo " DONE"; fi
 fi
 
 #===============================================================================
